version: '3.8'

services:
  server:
    container_name: server
    # restart: always
    build:
      context: ./server
      dockerfile: dockerfile.server
    ports:
      - "$SERVER_PORT:$SERVER_PORT"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      MONGO_URL: mongodb://mongodb:27017/$MONGODB_DATABASE
      SERVER_PORT: $SERVER_PORT
      JWT_SECRET: $JWT_SECRET
    depends_on:
      - mongodb
    command: yarn start:dev
  client:
    container_name: client
    # restart: always
    build:
      context: ./client
      dockerfile: dockerfile.client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    command: yarn start
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - '$MONGODB_PORT:27017'
    volumes:      
      - 'data:/data/db'
    command: mongod --bind_ip_all

volumes:
  data:
