version: '3.7'

services:
  dev:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://mongodb:27017/nest
      MONGODB_DATABASE: nest
    command: yarn start:dev
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:      
      - 'data:/data/db'
    command: mongod --bind_ip_all
volumes:
  data: